on: [push]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: sudo apt-get install avr-libc gcc-avr -y
    - uses: neomura/setup-aseprite-cli-action@v1.0.3
    - run: make
    # TODO: OpenSCAD
    # TODO: version injection
    - uses: INTI-CMNB/KiBot@v1_k6
      with:
        config: config.kibot.yaml
        schema: src/hardware/pcb/quantum_monster.kicad_sch
        board: src/hardware/pcb/quantum_monster.kicad_pcb
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
